### ISSUE TITLE
Too many aggressive calls to `fileExists()`

### ISSUE THREAD

**Issue by DeckerMMIV** [mInternauta/AgroSponsor#2]
May I suggest that you refactor the checks that is done in AgroSponsor.LUA [here](https://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L167) and [here](https://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L175).

Calling `fileExists()` at _each-and-every_ frame update (like 60 times a second) really causes FPS drops and bad performance.

It should suffice to check the existence of a file, only when the player actively chooses to save his game-session.

**Comment by mInternauta** [comment]
in fact you're right, but the reason for the AutoSave and precisely because in some situations the Save event is not triggered and does not save the data from AgroSponsor

Enviada do meu iPhone

Em 26/03/2016, ?s 10:05, "DeckerMMIV" <notifications@github.com<mailto:notifications@github.com>> escreveu:

May I suggest that you refactor the checks that is done in AgroSponsor.LUA herehttps://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L167 and herehttps://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L175.

Calling fileExists() at each-and-every frame update (like 60 times a second) really causes FPS drops and bad performance.

It should suffice to check the existence of a file, only when the player actively chooses to save his game-session.

##

**Comment by mInternauta** [comment]
I will check that soon

Enviada do meu iPhone

Em 26/03/2016, ?s 10:05, "DeckerMMIV" <notifications@github.com<mailto:notifications@github.com>> escreveu:

May I suggest that you refactor the checks that is done in AgroSponsor.LUA herehttps://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L167 and herehttps://github.com/mInternauta/AgroSponsor/blob/master/src/AgroSponsor.lua#L175.

Calling fileExists() at each-and-every frame update (like 60 times a second) really causes FPS drops and bad performance.

It should suffice to check the existence of a file, only when the player actively chooses to save his game-session.

##
